# -----------------------------------------------------------------------------
# Bundle the CSVs in results/ into dashboard/results.js for the static
# dashboard (index.html). Written as a JS file rather than JSON so the page
# also works when opened straight from disk.
#
# Run from the repository root after the analyses:  Rscript R/build_dashboard_data.R
# -----------------------------------------------------------------------------

suppressPackageStartupMessages({
  library(jsonlite)
})

read_dir <- function(dir) {
  files <- list.files(dir, pattern = "\\.csv$", full.names = TRUE)
  out <- lapply(files, read.csv, check.names = FALSE, stringsAsFactors = FALSE)
  names(out) <- tools::file_path_sans_ext(basename(files))
  out
}

results <- list(
  unsupervised = read_dir("results/01_unsupervised"),
  ssri = read_dir("results/02_ssri_response"),
  ssri_symptoms = read_dir("results/03_ssri_response_symptoms")
)

# Figures produced by R (dendrograms, density plots, ...) shown as images
results$figures <- lapply(
  c(unsupervised = "results/01_unsupervised/figures",
    ssri = "results/02_ssri_response/figures",
    ssri_symptoms = "results/03_ssri_response_symptoms/figures"),
  function(d) if (dir.exists(d)) file.path(d, list.files(d, pattern = "\\.png$")) else character()
)
results$generated <- format(Sys.Date())

dir.create("dashboard", showWarnings = FALSE)
writeLines(
  c("// Generated by R/build_dashboard_data.R - do not edit by hand.",
    paste0("window.RESULTS = ", toJSON(results, dataframe = "rows", digits = 4, auto_unbox = TRUE, na = "null"), ";")),
  "dashboard/results.js", useBytes = TRUE
)
cat("Wrote dashboard/results.js (", round(file.size("dashboard/results.js") / 1024), "KB )\n")
